### ISSUE TITLE
정한솔 Homework #01

### ISSUE THREAD

**Issue by Hansol-Jeong** [ai-creatv/java-jbd1#11]
https://github.com/Hansol-Jeong/java-til.git
git hub bash를 만지다가 git init으로 초기화시킨거같은데 그 이후 add가 안됩니다...어떻게 다시 연결할까요 8ㅅ8

**Comment by ai-creatv** [comment]
기존 폴더의 폴더명은 변경해 두시고, git clone을 다시 하셔서 새로 생성된 폴더에 작업하시면 됩니다.
