### ISSUE TITLE
최형중 HomeWork #1

### ISSUE THREAD

**Issue by wanni0928** [ai-creatv/java-jbd1#12]
# 1일차 복습내용 링크
* [https://github.com/wanni0928/java-til](https://github.com/wanni0928/java-til)

# 질문

* lowerCamelCase를 써야하는 경우와 UpperCalmelCase 경우에 대해 여쭤보고 싶습니다.
* ps. 제 개인적인 생각으로는 영어 문장에 주어의 맨 앞단어는 대문자로 쓰이는 영어의 특성상 '주어'처럼 쓰이는 것은 UpperCamelCase를 사용하고, '동사' 나 '목적어' 처럼 쓰이는 것은 lowerCamelCase로 쓰이는 것이라 생각했습니다.

**Comment by ai-creatv** [comment]
일반적으로 변수는 모두 lowerCamelCase를 사용합니다.

UpperCamelCase는 주로 클래스, Enum, static 및 final 변수 등에 사용합니다.
