### ISSUE TITLE
우혁준 - Homework 1

### ISSUE THREAD

**Issue by hwoo2394** [ai-creatv/java-jbd1#13]
SSH Key 찾는방법좀 다시한번 알려주세요

[우혁준 GitHub](https://github.com/hwoo2394/java-til)

**Comment by ai-creatv** [comment]
윈도우시라면 보통 '사용자' 폴더 내에 '.ssh' 폴더 안에 있습니다. 파일 검색으로 id_rsa.pub을 직접 찾으셔도 됩니다.

맥 사용자시면 ~/.ssh/ 위치에 있습니다.
