### ISSUE TITLE
정한솔 Homework#3 ٩(ˊᗜˋ*)و 

### ISSUE THREAD

**Issue by Hansol-Jeong** [ai-creatv/java-jbd1#38]
[숙제 4,5](https://github.com/Hansol-Jeong/java-til/tree/master/%EC%88%99%EC%A0%9C)

**Comment by ai-creatv** [comment]
충실하게 잘 구현해 주셨네요! 100/100

변수명을 정하실 때에는 배웠던 규칙을 이용하시는 것이 좋습니다. (lowerCamelCase)

또한 의미가 적절한 변수 (baby?)를 쓰시면 더 좋을 것 같네요! :)
