### ISSUE TITLE
천도희 Homework

### ISSUE THREAD

**Issue by chundh** [ai-creatv/java-jbd1#4]
git push하는 과정에서 "Updates were rejected because the remote contains work that you do not have locally" 라는 에러를 접했습니다. 구글링을 해서 git pull origin master를 한 후 git push를 하여 에러를 해결했는데 git pulll origin master가 어떤 기능을 하는지 궁금합니다.

https://github.com/chundh/java-til

**Comment by ai-creatv** [comment]
local에 있는 것 보다 remote에 있는 내용이 더 최신일 경우에 해당합니다. git pull origin master는 remote에 있는 최신 코드를 받아오는 역할을 합니다.
