### ISSUE TITLE
최형중 Homework #4

### ISSUE THREAD

**Issue by wanni0928** [ai-creatv/java-jbd1#52]
# Homework #4
* [Homework](https://github.com/wanni0928/java-til/tree/master/homework/day04)
* [TIL](https://github.com/wanni0928/java-til)

**Comment by ai-creatv** [comment]
충실하게 잘 구현해 주셨습니다 :) 100/100

O(n) 솔루션도 잘 숙지해 두시기 바랍니다 :)
