### ISSUE TITLE
최유선 homework #4

### ISSUE THREAD

**Issue by Yus2on** [ai-creatv/java-jbd1#57]
#### [배열의 연속된 합 최대값 구하기!!!!!!!!!!!!!](https://github.com/Yus2on/JAVA_TIL/blob/master/Homework/MaxSum/src/com/company/Main.java)

**Comment by ai-creatv** [comment]
잘 구현해 주셨네요 :) O(n) 솔루션도 잘 숙지하시면 도움이 언젠간 꼭 될겁니다 :)   100/100
