### ISSUE TITLE
최형중 Homework #5

### ISSUE THREAD

**Issue by wanni0928** [ai-creatv/java-jbd1#62]
# Homework#5
* [도메인 거꾸로](https://github.com/wanni0928/java-til/blob/master/homework/day05/DomainReverse.java)

**Comment by ai-creatv** [comment]
split과 StringBuffer를 이용해서 잘 구현해 주셨네요! 👍 100/100

참고로 단일 쓰레드에서는 StringBuffer보다는 StringBuilder를 쓰시는 것이 좋습니다.
