### ISSUE TITLE
배승현 HomeWorks #4, #5

### ISSUE THREAD

**Issue by ther3tyle** [ai-creatv/java-jbd1#64]
Day 4 이슈가 증발해서 묶어서 전달 드립니다..  :cold_sweat:
감사합니다!

-|TIL|Homework
-|-|-
DAY04|[TIL](https://github.com/ther3tyle/java-til/blob/master/src/io/dsub/lectures/day04/README.md)|[HomeWork](https://github.com/ther3tyle/java-til/tree/master/src/io/dsub/homework/day04)
DAY05|[TIL](https://github.com/ther3tyle/java-til/blob/master/src/io/dsub/lectures/day05/README.md)|[HomeWork](https://github.com/ther3tyle/java-til/tree/master/src/io/dsub/homework/day05)

**Comment by ai-creatv** [comment]
두 과제 모두 잘 해결해 주셨습니다! :) 100/100 100/100

5일차 과제의 경우 www.과 관련한 부분은 불필요한 부분인 것 같네요!

4일차의 O(n) 솔루션의 경우 유용하니 잘 숙지해 두시기 바랍니다 :)
