### ISSUE TITLE
김남호 Homework 01

### ISSUE THREAD

**Issue by NamhoGim** [ai-creatv/java-jbd1#7]
# 질문
아래 수업시간에 들어 주셨던 예시 처럼 type cast를 꼭 해 주어야 하는 경우가 또 있는지 궁금 합니다.

`short shortC = (short)(shortA + shortB);`

# TIL
https://github.com/NamhoGim/java-til

**Comment by ai-creatv** [comment]
byte byteC = (byte)(byteA + byteB); 처럼 byte의 경우에도 그렇습니다.

그 외에는 특별히 많지 않습니다만, 아래처럼 int끼리 연산할 때 long으로 미리 캐스팅하면 오버플로우를 방지할 수 있습니다.

long longVal = (long)intA + (long)intB;

**Comment by NamhoGim** [comment]
답이 충분히 되었습니다. 감사합니다.
