### ISSUE TITLE
김동훈 Homework#5

### ISSUE THREAD

**Issue by gompd** [ai-creatv/java-jbd1#75]
[Homework](https://github.com/gompd/java-fil/tree/master/Homework2%20%235/src/com/company)

**Comment by ai-creatv** [comment]
Split을 이용해서 간결하게 잘 구현해 주셨네요!!

마지막에 .이 하나 추가로 붙게 구현된 점 확인 부탁드립니다 :) 

그리고 코딩중에 위쪽에 자동으로 작성된 import 중에 필요 없는 부분은 제거해 주시는 것이 좋습니다!

100/100.
