### ISSUE TITLE
배승현 homework #01

### ISSUE THREAD

**Issue by ther3tyle** [ai-creatv/java-jbd1#8]
__*question*__
```
short shortA = 10, shortB = 20;
short shortC = (short) (shortA + shortB);
```
위의 코드에서 short -> int -> short 로 형이 변환되는지, 혹은 알아서 Short -> Short 로 처리되는지가 궁금합니다!

__*homework*__
[https://github.com/ther3tyle/java-til](url)

**Comment by ai-creatv** [comment]
정확하게는 아래와 같이 연산이 이루어집니다.

- shortA와 shortB 각각 int로 먼저 변환이 된다.
- + 연산이 이루어진다.
- short로 변환된다.
