### ISSUE TITLE
임준철의 homework #6

### ISSUE THREAD

**Issue by limjoonchul** [ai-creatv/java-jbd1#85]
[homework](https://github.com/limjoonchul/java-TIL/tree/master/homeworkDay6)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다 :) 90/100

MyMath의 ceil과 floor의 경우 출제 의도상, 직접 구현해 주셨으면 더 좋겠습니다!

Vector3D의 경우 일부 연산이 원본을 수정하는 동작을 하네요. 원본을 수정하거나, 새로운 객체를 생성하거나 둘 중 하나로 동작을 통일해 주시면 좋습니다 :)
