### ISSUE TITLE
정한솔HomeWork#06

### ISSUE THREAD

**Issue by Hansol-Jeong** [ai-creatv/java-jbd1#87]
[숙제 9, 10, 11](https://github.com/Hansol-Jeong/java-til/tree/master/HomeWork)

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! :) 80/100

MyMath의 경우 명세에 정수/실수에 대해 동작해야 하는 조건이 있기 때문에, 오버로딩을 해 주셔야 합니다!

싱글톤 패턴의 경우 instance가 public으로 되어 있는데, private으로 해야만 합니다.

Vector3D의 경우 코딩 스타일을 답안을 참조하시면서 더 가독성 좋은 코드의 작성법을 익혀 주세요 :)
